# Generated by Django 4.2 on 2023-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ('-created_at',)},
        ),
    ]
